import React from 'react';
import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {MemoryRouter,Routes,Route,useLocation} from 'react-router-dom';
import SecuritySanctumPage from '../../src/pages/SecuritySanctumPage';
import useAuth from '../../src/hooks/useAuth';
import * as api from '../../src/api/usersApi';
jest.mock('../../src/hooks/useAuth');
jest.mock('../../src/api/usersApi',()=>({getSessionsApi:jest.fn(),revokeSessionApi:jest.fn(),revokeOtherSessionsApi:jest.fn(),changePasswordApi:jest.fn()}));
const forget=jest.fn();
const rows=[{id:1,current:true,user_agent:'Chrome/120 Windows',ip_address:'127.0.0.1',expires_at:'2026-09-12T00:00:00Z'},{id:2,current:false,user_agent:'Firefox/130 Linux',ip_address:'192.0.2.2',expires_at:'2026-09-12T00:00:00Z'}];
function Login(){const location=useLocation();return <p>{location.state?.securityMessage}</p>;}
function display(){return render(<MemoryRouter initialEntries={['/settings/security']}><Routes><Route path="/settings/security" element={<SecuritySanctumPage/>}/><Route path="/login" element={<Login/>}/></Routes></MemoryRouter>);}
beforeEach(()=>{jest.resetAllMocks();useAuth.mockReturnValue({forgetSession:forget});api.getSessionsApi.mockResolvedValue({data:rows});api.revokeSessionApi.mockResolvedValue({data:{revoked:1,currentRevoked:false}});api.revokeOtherSessionsApi.mockResolvedValue({data:{revoked:1,currentRevoked:false}});api.changePasswordApi.mockResolvedValue({data:{message:'Password changed. Sign in again.'}});});
async function fill(user,confirm='replacement-password'){await user.type(screen.getByLabelText('Current password'),'original-password');await user.type(screen.getByLabelText('New password'),'replacement-password');await user.type(screen.getByLabelText('Confirm new password'),confirm);await user.click(screen.getByRole('button',{name:'Change password & sign out'}));}
test('shows current session and browser metadata',async()=>{display();await screen.findByText('This session');expect(screen.getByText('IP: 192.0.2.2')).toBeInTheDocument();expect(screen.getByText('Firefox · Linux')).toBeInTheDocument();});
test('canceling revocation never calls the API',async()=>{const user=userEvent.setup();display();await user.click(await screen.findByRole('button',{name:'Sign out session 2'}));expect(api.revokeSessionApi).not.toHaveBeenCalled();await user.click(screen.getByText('Cancel'));expect(api.revokeSessionApi).not.toHaveBeenCalled();});
test('confirmed revocation targets the selected session and reloads',async()=>{const user=userEvent.setup();display();await user.click(await screen.findByRole('button',{name:'Sign out session 2'}));await user.click(screen.getByText('Confirm sign out'));await screen.findByText('1 session signed out.');expect(api.revokeSessionApi).toHaveBeenCalledWith(2);expect(api.getSessionsApi).toHaveBeenCalledTimes(2);expect(forget).not.toHaveBeenCalled();});
test('sign out others uses the scoped endpoint',async()=>{const user=userEvent.setup();display();await screen.findByText('This session');await user.click(screen.getByText('Sign out other sessions'));await user.click(screen.getByText('Confirm sign out'));await waitFor(()=>expect(api.revokeOtherSessionsApi).toHaveBeenCalledTimes(1));expect(api.revokeSessionApi).not.toHaveBeenCalled();});
test('revoking current session clears local authentication and navigates',async()=>{api.revokeSessionApi.mockResolvedValue({data:{revoked:1,currentRevoked:true}});const user=userEvent.setup();display();await user.click(await screen.findByRole('button',{name:'Sign out session 1'}));await user.click(screen.getByText('Confirm sign out'));await screen.findByText('This session has been signed out.');expect(forget).toHaveBeenCalledTimes(1);});
test('password mismatch prevents submission',async()=>{const user=userEvent.setup();display();await screen.findByText('This session');await fill(user,'different-password');await screen.findByText('The new passwords do not match.');expect(api.changePasswordApi).not.toHaveBeenCalled();});
test('incorrect current password keeps the user on the page',async()=>{api.changePasswordApi.mockRejectedValue({response:{data:{error:'Current password is incorrect.'}}});const user=userEvent.setup();display();await screen.findByText('This session');await fill(user);await screen.findByText('Current password is incorrect.');expect(forget).not.toHaveBeenCalled();});
test('successful password change clears authentication and explains sign-in',async()=>{const user=userEvent.setup();display();await screen.findByText('This session');await fill(user);await screen.findByText('Password changed. Sign in again.');expect(api.changePasswordApi).toHaveBeenCalledWith({currentPassword:'original-password',newPassword:'replacement-password'});expect(forget).toHaveBeenCalledTimes(1);});
test('failed revocation preserves local authentication',async()=>{api.revokeSessionApi.mockRejectedValue(new Error('offline'));const user=userEvent.setup();display();await user.click(await screen.findByRole('button',{name:'Sign out session 1'}));await user.click(screen.getByText('Confirm sign out'));await screen.findByText('Revocation could not be confirmed. Refresh and check the session list.');expect(forget).not.toHaveBeenCalled();});
test('session load failure offers retry',async()=>{api.getSessionsApi.mockRejectedValueOnce(new Error('offline'));const user=userEvent.setup();display();await screen.findByText('Unable to load active sessions. Please retry.');await user.click(screen.getByText('Refresh sessions'));await screen.findByText('This session');});
