import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import useAuth from '../hooks/useAuth';
import { PageHeading, Notice, Loading, Empty, money } from '../components/common/Imperial';
import * as api from '../api/adminApi';
import { getDisputesApi } from '../api/disputesApi';
import { storeImpersonation, navigateImpersonation } from '../services/impersonationService';
const tabs = { overview: 'Overview', users: 'Users', vaults: 'Vaults', disputes: 'Disputes', audit: 'Audit trail' };
const metrics = { users: 'Active users', pendingUsers: 'Awaiting verification', admins: 'Administrators', vaults: 'Active vaults', openDisputes: 'Open disputes', reviewDisputes: 'Under review', sessions: 'Active sessions', failedEmail: 'Failed email deliveries' };
const statuses = { users: [['active', 'Verified users'], ['pending', 'Pending verification'], ['admins', 'Administrators'], ['archived', 'Archived users']], vaults: [['active', 'Active vaults'], ['archived', 'Archived vaults']], disputes: [['Open', 'Open'], ['UnderReview', 'Under review'], ['Resolved', 'Resolved'], ['Rejected', 'Rejected'], ['Withdrawn', 'Withdrawn']] };
function AuditDetails({ value }) { let data; try { data = JSON.parse(value); } catch { return <p>{value}</p>; } if (data?.caseId) return <p><Link className="text-link" to={`/admin/disputes/${data.caseId}`}>Case #{data.caseId}</Link> · {data.status}</p>; return <><p>Target user #{data?.targetUserId ?? '—'}{typeof data?.admin === 'boolean' && ` · Role: ${data.admin ? 'Administrator' : 'Member'}`}{data?.revokedSessions != null && ` · ${data.revokedSessions} sessions revoked`}</p><p className="case-prose">{data?.reason || data?.source || 'Administrative event'}</p></>; }
export default function AdminPage() {
    const { user } = useAuth();
    return user?.super_user ? <AdminConsole user={user} /> : <div className="workspace"><PageHeading eyebrow="RESTRICTED COMMAND" title="Administrator access required." /><Link className="btn btn-outline" to="/dashboard">Return to vault command</Link></div>;
}
function AdminConsole({ user }) {
    const [params] = useSearchParams();
    const [tab, setTab] = useState(() => Object.keys(tabs).includes(params.get('section')) ? params.get('section') : 'overview'), [query, setQuery] = useState({ q: '', status: '' }), [search, setSearch] = useState(''), [overview, setOverview] = useState(null), [items, setItems] = useState([]), [next, setNext] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [message, setMessage] = useState(''), [denied, setDenied] = useState(false);
    const [pending, setPending] = useState(null), [reason, setReason] = useState(''), [confirmEmail, setConfirmEmail] = useState(''), [busy, setBusy] = useState(false);
    const sequence = useRef(0), flight = useRef(false), heading = useRef(null);
    const load = useCallback(async before => {
        const request = ++sequence.current; setLoading(true); setError('');
        try { const params = { ...(query.q ? { q: query.q } : {}), ...(query.status ? { status: query.status } : {}), ...(before ? { before } : {}) };
            const { data } = await (tab === 'overview' ? api.getAdminOverviewApi() : tab === 'users' ? api.getAdminUsersApi(params) : tab === 'vaults' ? api.getAdminVaultsApi(params) : tab === 'audit' ? api.getAdminAuditApi(params) : getDisputesApi({ ...params, scope: 'review' }));
            if (request !== sequence.current) return;
            if (tab === 'overview') setOverview(data); else { setItems(old => before ? [...old, ...data.items.filter(row => !old.some(item => item.id === row.id))] : data.items); setNext(data.next); }
        } catch (err) { if (request === sequence.current) { setError(err.response?.data?.error || 'The admin register could not be loaded. Please retry.'); if ([401, 403].includes(err.response?.status)) { setDenied(true); setItems([]); setOverview(null); } } }
        finally { if (request === sequence.current) setLoading(false); }
    }, [tab, query]);
    useEffect(() => { const requests = sequence; setItems([]); setNext(null); load(); return () => { requests.current++; }; }, [load]);
    useEffect(() => { if (pending) heading.current?.focus(); }, [pending]);
    function choose(key) { setTab(key); setQuery({ q: '', status: '' }); setSearch(''); setMessage(''); setPending(null); }
    function review(row, action) { setReason(''); setConfirmEmail(''); setPending({ row, action }); setMessage(''); }
    async function commit(event) {
        event.preventDefault(); if (flight.current || confirmEmail !== pending.row.email) return; flight.current = true; setBusy(true); setError(''); setMessage('');
        if (pending.action === 'impersonate') {
            try { const { data } = await api.startImpersonationApi(pending.row.id, { reason: reason.trim() });
                try { storeImpersonation(data); } catch (error) { await api.stopImpersonationApi(data.id); throw error; }
                navigateImpersonation('/dashboard');
            } catch (err) { setError(err.response?.data?.error || 'Unable to start impersonation. Check that browser session storage is available and retry.'); }
            finally { flight.current = false; setBusy(false); }
            return;
        }
        try { const { data } = await (pending.action === 'role' ? api.changeAdminRoleApi(pending.row.id, { super_user: !pending.row.super_user, expectedRole: Boolean(pending.row.super_user), reason: reason.trim() }) : api.revokeAdminSessionsApi(pending.row.id, { reason: reason.trim() }));
            setPending(null); setMessage(data.message); await load();
        } catch (err) { setError(err.response?.data?.error || 'The action could not be confirmed. Refresh the directory before retrying.'); setPending(null); if ([401, 403].includes(err.response?.status)) { setDenied(true); setItems([]); setOverview(null); } }
        finally { flight.current = false; setBusy(false); }
    }
    return <div className="workspace admin-workspace"><Link className="back-link" to="/dashboard">← Personal vault command</Link><PageHeading eyebrow="HIGH LORDS OF TERRA / ADMINISTRATIVE COMMAND" title="The Administratum." action={<span className="badge badge-gold">ADMINISTRATOR</span>}>Oversee the registry, review ledger disputes, and govern account access.</PageHeading>
        {error && <Notice error>{error}</Notice>}{message && <Notice>{message}</Notice>}
        {!denied && <><div className="admin-toolbar"><nav aria-label="Admin sections" className="admin-tabs">{Object.entries(tabs).map(([key, name]) => <button key={key} className={`btn ${tab === key ? 'btn-primary' : 'btn-outline'}`} aria-pressed={tab === key} disabled={busy || Boolean(pending)} onClick={() => choose(key)}>{name}</button>)}</nav><button className="btn btn-quiet" disabled={loading || busy || Boolean(pending)} onClick={() => load()}>Refresh register</button></div>
        {tab !== 'overview' && tab !== 'audit' && <form className="admin-filters" onSubmit={event => { event.preventDefault(); setQuery(q => ({ ...q, q: search.trim() })); }}>{tab !== 'disputes' && <><label>Search {tab}<input maxLength={100} value={search} disabled={busy || Boolean(pending)} onChange={e => setSearch(e.target.value)} placeholder={tab === 'users' ? 'Email or user ID' : 'Vault name or ID'} /></label><button className="btn btn-outline" disabled={busy || Boolean(pending)}>Search</button></>}<label>Filter {tab}<select value={query.status} disabled={busy || Boolean(pending)} onChange={e => setQuery(q => ({ ...q, status: e.target.value }))}><option value="">All</option>{statuses[tab].map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label></form>}
        {pending && <section className="form-panel settings-confirm"><h2 ref={heading} tabIndex={-1}>Confirm administrative action</h2><p>{pending.action === 'role' ? `${pending.row.super_user ? 'Remove administrator access from' : 'Grant administrator access to'} ${pending.row.email}.` : pending.action === 'impersonate' ? `View ${pending.row.email} with read-only support access for up to 15 minutes.` : `Sign out all sessions belonging to ${pending.row.email}.`}</p><p className="muted">{pending.action === 'impersonate' ? 'The member stays signed in. Your admin session is preserved, and the support session is recorded in the audit trail.' : 'The user must sign in again. Your reason will be retained in the audit trail.'}</p><form onSubmit={commit}><fieldset className="security-fieldset" disabled={busy}><label>Administrative reason<textarea required minLength={5} maxLength={500} value={reason} onChange={e => setReason(e.target.value)} /></label><label>Type the account email to confirm<input required value={confirmEmail} onChange={e => setConfirmEmail(e.target.value)} autoComplete="off" /></label><div className="button-row"><button className="btn btn-primary" disabled={confirmEmail !== pending.row.email}>Confirm action</button><button type="button" className="btn btn-quiet" onClick={() => setPending(null)}>Cancel</button></div></fieldset></form></section>}
        {loading && <Loading label="Consulting administrative records" />}
        {!loading && tab === 'overview' && overview && <><div className="admin-metrics">{Object.entries(metrics).map(([key, text]) => <section className="admin-metric" key={key}><p className="eyebrow">{text}</p><strong>{overview[key]}</strong></section>)}</div><section className="form-panel"><h2>Orders requiring attention</h2><div className="button-row"><button className="btn btn-outline" onClick={() => { choose('disputes'); setQuery({ q: '', status: 'Open' }); }}>Review open disputes →</button><button className="btn btn-outline" onClick={() => { choose('users'); setQuery({ q: '', status: 'pending' }); }}>View pending users →</button></div><p className="muted">Email failures are deliveries that exhausted retries or received a permanent rejection. These counts reflect stored records, not a live SMTP health test.</p><p className="fine-print">Last checked: {new Date(overview.checkedAt).toLocaleString()}</p></section></>}
        {!loading && !error && tab !== 'overview' && !items.length && <Empty title="No matching records.">Adjust your filters or refresh the register.</Empty>}
        {tab === 'users' && <div className="admin-records">{items.map(row => <article className="admin-record" key={row.id}><div><span className="eyebrow">CITIZEN #{row.id}</span><h2>{row.email || 'Archived account'}</h2><p>{row.archived ? 'Archived' : row.verified ? 'Verified' : 'Pending verification'} · {row.super_user ? 'Administrator' : 'Member'}{row.id === user.id ? ' · You' : ''}</p></div><div className="button-row">{row.id !== user.id && !row.archived && row.verified && <><button className="btn btn-outline" disabled={busy || Boolean(pending)} onClick={() => review(row, 'role')}>{row.super_user ? 'Remove admin' : 'Grant admin'}</button><button className="btn btn-quiet" disabled={busy || Boolean(pending)} onClick={() => review(row, 'sessions')}>Revoke sessions</button>{!row.super_user && <button className="btn btn-outline" disabled={busy || Boolean(pending)} onClick={() => review(row, 'impersonate')}>Impersonate</button>}</>}{row.id === user.id && <Link className="text-link" to="/settings/security">Manage your sessions →</Link>}</div></article>)}</div>}
        {tab === 'vaults' && <div className="admin-records">{items.map(row => <article className="admin-record" key={row.id}><div><span className="eyebrow">VAULT #{row.id} / {row.archived ? 'ARCHIVED' : 'ACTIVE'}</span><h2>{row.name}</h2><p>Owner: {row.users?.email || `User #${row.owner}`} · {row.type}</p><p className="muted">Overdraft: {row.overdraft ? 'Allowed' : 'Not allowed'}</p></div><strong className="vault-balance">{money(row.balance)} ₮</strong></article>)}</div>}
        {tab === 'disputes' && <ul className="case-list">{items.map(row => <li key={row.id}><Link to={`/admin/disputes/${row.id}`}><div><span className="eyebrow">CASE #{row.id} / TRANSACTION #{row.transaction_id}</span><h3>{row.reason}</h3><p>Reporter #{row.user_id}{row.user_id === user.id ? ' · Your case requires another administrator' : ''}</p></div><span className="badge badge-gold">{row.status === 'UnderReview' ? 'Under review' : row.status}</span></Link></li>)}</ul>}
        {tab === 'audit' && <ol className="case-history">{items.map(row => <li key={row.id}><span className="eyebrow">{row.action.replaceAll('_', ' ')} / ADMIN #{row.user_id}</span><AuditDetails value={row.details} /><time>{row.create_date && new Date(row.create_date).toLocaleString()}</time></li>)}</ol>}
        {next && tab !== 'overview' && <button className="btn btn-outline" disabled={loading || busy || Boolean(pending)} onClick={() => load(next)}>Load older records</button>}</>}
    </div>;
}
