import React from 'react';
import { Link } from 'react-router-dom';
import useAuth from '../hooks/useAuth';
import { Aquila, Sigil } from '../components/common/Imperial';
export default function HomePage() {
  const {
    user
  } = useAuth();
  return <div className="home"><section className="hero"><div className="hero-copy"><p className="eyebrow">✦ BY DECREE OF THE GOLDEN THRONE</p><h1>Wealth is duty.<br /><em>Duty is eternal.</em></h1><p className="hero-description">In an age of endless war, your holdings endure. Entrust your throne gelt to the vaults of Holy Terra.</p><div className="button-row"><Link className="btn btn-primary" to={user ? '/dashboard' : '/register'}>{user ? 'Enter vault command' : 'Pledge your holdings'} ↗</Link><Link className="text-link" to={user ? '/account/create' : '/login'}>{user ? 'Establish a vault' : 'Already enlisted? Access vault'} →</Link></div><div className="hero-caption"><span>EST. M31</span><span className="rule" /><span>IN SERVICE TO THE IMPERIUM</span></div></div><div className="reliquary" aria-label="Imperial Aquila insignia"><div className="reliquary-top">SIGILLUM IMPERIALIS <span>001 / TERRA</span></div><div className="reliquary-icon"><Aquila /><span className="reliquary-letter">I</span></div><div className="reliquary-bottom"><p>THE IMPERIAL TREASURY</p><strong>Faith. Fortitude. Fortune.</strong><span>++ THE EMPEROR PROTECTS ++</span></div></div></section><div className="edict-band"><span>IMPERIAL EDICT / 001</span><p>“To serve the Emperor is to serve mankind.”</p><span aria-hidden="true">✦</span></div><section className="service-section"><div className="section-heading-row"><div><p className="eyebrow">SANCTIONED OPERATIONS</p><h2>Your place in the great ledger.</h2></div><Link className="text-link" to="/about">Read the charter →</Link></div><div className="service-grid">{[['I', 'Establish your vault', 'Create a dedicated home for your throne gelt. Every holding, accounted for.', user ? '/account/create' : '/register', 'Establish a vault'], ['II', 'Command your holdings', 'Review your balances and record each deposit and withdrawal in the ledger.', user ? '/dashboard' : '/login', 'Enter vault command'], ['III', 'Consult the archives', 'Find guidance on account access, verification, and the rites of banking.', '/help', 'Open the archives']].map(([n, title, text, url, link]) => <article className="service-card" key={n}><Sigil>{n}</Sigil><h3>{title}</h3><p>{text}</p><Link className="text-link" to={url}>{link} →</Link></article>)}</div></section></div>;
}
