import React,{useCallback,useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {getLedgerLabelsApi,saveLedgerLabelApi,archiveLedgerLabelApi} from '../api/ledgerLabelsApi';
import {PageHeading,Loading,Notice,Empty} from '../components/common/Imperial';
const blank={name:'',color:'#c1a267',kind:'category'};
export default function LedgerLabelsPage(){
 const [catalog,setCatalog]=useState(null),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 const flight=useRef(false),alive=useRef(true),input=useRef(null);
 const load=useCallback(async()=>{try{const data=await getLedgerLabelsApi();if(alive.current)setCatalog(data);}catch{if(alive.current)setError('The label register could not be loaded. Please retry.');}},[]);
 useEffect(()=>{alive.current=true;load();return()=>{alive.current=false;};},[load]);
 async function act(operation,message){if(flight.current)return;flight.current=true;setBusy(true);setError('');setStatus('');try{await operation();if(alive.current){setForm(blank);setEditing(null);setStatus(message);await load();}}catch(err){if(alive.current)setError(err.response?.data?.error||'The change could not be confirmed. Refresh before retrying.');}finally{flight.current=false;if(alive.current)setBusy(false);}}
 return <div className="workspace"><Link className="back-link" to="/archives">← Ledger archives</Link><PageHeading eyebrow="ADMINISTRATUM / PERSONAL CLASSIFICATION" title="Order the ledger.">Create categories and colored tags for your own view of the ledger. Other vault members keep their own labels.</PageHeading>{error&&<Notice error>{error} <button className="btn btn-quiet" disabled={busy} onClick={load}>Refresh labels</button></Notice>}{status&&<Notice>{status}</Notice>}
 <section className="form-panel"><h2>{editing?'Edit label':'Create a label'}</h2><form onSubmit={e=>{e.preventDefault();act(()=>saveLedgerLabelApi(form.kind,{name:form.name.trim(),color:form.color},editing?.id),editing?'Label updated.':'Label created.');}}><fieldset className="security-fieldset" disabled={busy}><div className="label-create-grid"><label>Label type<select value={form.kind} disabled={Boolean(editing)} onChange={e=>setForm({...form,kind:e.target.value})}><option value="category">Category</option><option value="tag">Tag</option></select></label><label>Label name<input ref={input} required maxLength={60} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Label color<input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label></div><div className="button-row"><button className="btn btn-primary">{editing?'Save label':'Create label'}</button>{editing&&<button className="btn btn-quiet" type="button" onClick={()=>{setEditing(null);setForm(blank);}}>Cancel edit</button>}</div></fieldset></form></section>
 {!catalog&&!error&&<Loading label="Reading the classification register"/>}{catalog&&<div className="preferences-grid">{[['Categories',catalog.categories],['Tags',catalog.tags]].map(([title,rows])=><section className="form-panel" key={title}><h2>{title}</h2>{!rows.length&&<Empty title={`No ${title.toLowerCase()} yet.`}>Create your first label above.</Empty>}<ul className="label-register">{rows.map(row=><li key={row.id}><div><span className="ledger-tag" style={{borderColor:row.color}}><span style={{backgroundColor:row.color}}/>{row.name}</span>{row.archived&&<small> Archived</small>}</div><div className="button-row"><button className="btn btn-quiet" disabled={busy} aria-label={`Edit ${row.name}`} onClick={()=>{setEditing(row);setForm({name:row.name,color:row.color,kind:row.kind});input.current?.focus();}}>Edit</button><button className="btn btn-quiet" disabled={busy} aria-label={`${row.archived?'Restore':'Archive'} ${row.name}`} onClick={()=>act(()=>row.archived?saveLedgerLabelApi(row.kind,{name:row.name,color:row.color,archived:false},row.id):archiveLedgerLabelApi(row.kind,row.id),row.archived?'Label restored.':'Label archived. Existing assignments remain visible.')}>{row.archived?'Restore':'Archive'}</button></div></li>)}</ul></section>)}</div>}<p className="fine-print">Renaming updates your assigned entries and reports. Archived labels stay on existing entries and remain filterable, but cannot be newly assigned. Use Ledger archives to select entries and apply labels.</p></div>;
}
