import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import useAuth from '../hooks/useAuth';
import { getSessionsApi, revokeSessionApi, revokeOtherSessionsApi, changePasswordApi } from '../api/usersApi';
import { PageHeading, Loading, Notice } from '../components/common/Imperial';
export function deviceLabel(agent = '') {
    const browser = /Edg\//.test(agent) ? 'Edge' : /Firefox\//.test(agent) ? 'Firefox' : /Chrome\//.test(agent) ? 'Chrome' : /Safari\//.test(agent) ? 'Safari' : 'Unknown browser';
    const platform = /Android/.test(agent) ? 'Android' : /iPhone|iPad/.test(agent) ? 'iOS' : /Windows/.test(agent) ? 'Windows' : /Macintosh/.test(agent) ? 'macOS' : /Linux/.test(agent) ? 'Linux' : 'Unknown device';
    return `${browser} · ${platform}`;
}
export default function SecuritySanctumPage() {
    const { forgetSession } = useAuth(), navigate = useNavigate();
    const [sessions, setSessions] = useState([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(''), [status, setStatus] = useState('');
    const [form, setForm] = useState({ currentPassword: '', newPassword: '', confirm: '' }), [pending, setPending] = useState(null);
    const alive = useRef(true), flight = useRef(false), heading = useRef(null);
    const load = useCallback(async () => { setLoading(true); try { const { data } = await getSessionsApi(); if (alive.current) { setSessions(data); setError(''); } } catch { if (alive.current) setError('Unable to load active sessions. Please retry.'); } finally { if (alive.current) setLoading(false); } }, []);
    useEffect(() => { alive.current = true; load(); return () => { alive.current = false; }; }, [load]);
    useEffect(() => { if (pending) heading.current?.focus(); }, [pending]);
    const signOut = message => { navigate('/login', { replace: true, state: { securityMessage: message } }); forgetSession(); };
    async function revoke() { if (flight.current) return; flight.current = true; setBusy(true); setError(''); try { const { data } = pending === 'others' ? await revokeOtherSessionsApi() : await revokeSessionApi(pending.id); if (!alive.current) return; setPending(null); if (data.currentRevoked) { signOut('This session has been signed out.'); return; } setStatus(`${data.revoked} session${data.revoked === 1 ? '' : 's'} signed out.`); await load(); } catch { if (alive.current) setError('Revocation could not be confirmed. Refresh and check the session list.'); } finally { flight.current = false; if (alive.current) setBusy(false); } }
    async function change(event) { event.preventDefault(); if (flight.current) return; setError(''); setStatus(''); if (form.newPassword !== form.confirm) { setError('The new passwords do not match.'); return; } if (new TextEncoder().encode(form.newPassword).length > 72) { setError('The new password must fit within 72 UTF-8 bytes.'); return; } flight.current = true; setBusy(true); try { const { data } = await changePasswordApi({ currentPassword: form.currentPassword, newPassword: form.newPassword }); if (alive.current) { setForm({ currentPassword: '', newPassword: '', confirm: '' }); signOut(data.message); } } catch (err) { if (alive.current) setError(err.response?.data?.error || 'The password change could not be confirmed. Try signing in with your new password before retrying.'); } finally { flight.current = false; if (alive.current) setBusy(false); } }
    return <div className="workspace security-sanctum"><PageHeading eyebrow="IMPERIAL SECURITY / IDENTITY COMMAND" title="Guard your access.">Manage your security cipher and the sessions authorized to enter your vaults.</PageHeading>{error && <Notice error>{error}</Notice>}{status && <Notice>{status}</Notice>}
        <div className="security-settings-grid"><section className="form-panel"><p className="eyebrow">CIPHER REFORGING</p><h2>Change password</h2><p className="muted">Changing your password signs out every session, including this one, and sends you a security email.</p><form onSubmit={change}><fieldset disabled={busy || Boolean(pending)} className="security-fieldset"><label>Current password<input type="password" required autoComplete="current-password" value={form.currentPassword} onChange={e => setForm({ ...form, currentPassword: e.target.value })} /></label><label>New password<input type="password" required minLength={8} maxLength={72} autoComplete="new-password" value={form.newPassword} onChange={e => setForm({ ...form, newPassword: e.target.value })} /></label><label>Confirm new password<input type="password" required minLength={8} maxLength={72} autoComplete="new-password" value={form.confirm} onChange={e => setForm({ ...form, confirm: e.target.value })} /></label><p className="fine-print">At least 8 characters, up to 72 UTF-8 bytes. Use a unique password.</p><button className="btn btn-primary">Change password & sign out</button></fieldset></form></section>
            <aside className="security-protocol"><p className="eyebrow">VIGILANCE PROTOCOL</p><h2>The Emperor protects.<br />Secure your sessions.</h2><p>Every sign-in creates a separate session. Signing out one device leaves the others active.</p><p>Revoke an unfamiliar session below. Its next request will be denied, including attempts to refresh its access token.</p><p className="fine-print">Device names are inferred from browser information and can be imitated. IP addresses may be shared by several devices. Activity updates at most once per minute.</p></aside></div>
        <section className="form-panel security-sessions"><div className="section-heading-row"><div><p className="eyebrow">AUTHORIZED CONNECTIONS</p><h2>Active sessions</h2></div><div className="button-row"><button className="btn btn-quiet" disabled={busy || loading} onClick={load}>Refresh sessions</button><button className="btn btn-outline" disabled={busy || loading || !sessions.some(row => !row.current)} onClick={() => setPending('others')}>Sign out other sessions</button></div></div>
            {pending && <div className="settings-confirm"><h3 ref={heading} tabIndex={-1}>Confirm session revocation</h3><p>{pending === 'others' ? 'All sessions except this one will lose access.' : pending.current ? 'This is your current session. You will be signed out.' : `${deviceLabel(pending.user_agent)} will lose access.`}</p><div className="button-row"><button className="btn btn-primary" disabled={busy} onClick={revoke}>Confirm sign out</button><button className="btn btn-quiet" disabled={busy} onClick={() => setPending(null)}>Cancel</button></div></div>}
            {loading && <Loading label="Checking active connections" />}<ul className="session-list">{sessions.map(row => <li key={row.id}><div><h3>{deviceLabel(row.user_agent)} {row.current && <span className="badge badge-gold">This session</span>}</h3><p>IP: {row.ip_address}</p><p>Signed in: {row.create_date ? new Date(row.create_date).toLocaleString() : 'Unknown'}<br />Last active: {row.update_date ? new Date(row.update_date).toLocaleString() : 'Unknown'}<br />Expires: {new Date(row.expires_at).toLocaleString()}</p><details><summary>Browser details</summary><p>{row.user_agent || 'Not provided'}</p></details></div><button className="btn btn-outline" aria-label={`Sign out session ${row.id}`} disabled={busy || Boolean(pending)} onClick={() => setPending(row)}>Sign out</button></li>)}</ul></section></div>;
}
