import React,{useRef,useState} from 'react';
import {assignLedgerLabelsApi} from '../../api/ledgerLabelsApi';
import {Notice} from './Imperial';
export default function LedgerLabelActions({selected,catalog,onSaved,disabled,onBusy}){
 const [category,setCategory]=useState(''),[tag,setTag]=useState(''),[action,setAction]=useState('add'),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const flight=useRef(false);
 function prepare(e){e.preventDefault();setError('');const payload={transactionIds:[...selected],...(category?{categoryId:category==='original'?null:Number(category)}:{}),...(tag?{[action==='add'?'addTagIds':'removeTagIds']:[Number(tag)]}:{})};setReview(payload);onBusy(true);}
 async function save(){if(flight.current)return;flight.current=true;setBusy(true);setError('');try{await assignLedgerLabelsApi(review);setReview(null);setCategory('');setTag('');onBusy(false);await onSaved();}catch(err){setError(err.response?.data?.error||'Labels could not be confirmed. Refresh the ledger before retrying.');}finally{flight.current=false;setBusy(false);}}
 return <section className="form-panel label-actions"><h3>Organize selected entries · {selected.length}</h3><p className="fine-print">Up to 100 entries per update. Changes affect only your categories and tags, never amounts or other members’ views.</p>{error&&<Notice error>{error}</Notice>}<form onSubmit={prepare}><fieldset disabled={disabled||busy||Boolean(review)||!selected.length} className="security-fieldset"><div className="label-create-grid"><label>Assign category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Keep current category</option><option value="original">Use original category</option>{catalog.categories.filter(row=>!row.archived).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Tag action<select value={action} onChange={e=>{setAction(e.target.value);setTag('');}}><option value="add">Add tag</option><option value="remove">Remove tag</option></select></label><label>Choose tag<select value={tag} onChange={e=>setTag(e.target.value)}><option value="">No tag change</option>{catalog.tags.filter(row=>action==='remove'||!row.archived).map(row=><option key={row.id} value={row.id}>{row.name}{row.archived?' (archived)':''}</option>)}</select></label></div><button className="btn btn-outline" disabled={!category&&!tag}>Review label changes</button></fieldset></form>{review&&<div className="settings-confirm"><h3>Confirm label changes</h3><p>Update {review.transactionIds.length} selected entries.</p>{category&&<p>Category: {category==='original'?'Original category':catalog.categories.find(row=>String(row.id)===category)?.name}</p>}{tag&&<p>{action==='add'?'Add':'Remove'} tag: {catalog.tags.find(row=>String(row.id)===tag)?.name}</p>}<div className="button-row"><button className="btn btn-primary" disabled={busy} onClick={save}>Confirm label changes</button><button className="btn btn-quiet" disabled={busy} onClick={()=>{setReview(null);onBusy(false);}}>Cancel label changes</button></div></div>}</section>;
}
